os:
  - linux
  # - osx
env:
  - NOWAL=1
language: python
python:
  - "2.7"
cache: pip
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install Cython --install-option="--no-cython-compile"
  - pip install coverage pytest pytest-cov
  - pip install lxml pyteomics brain-isotopic-distribution
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -r external-requirements.txt
  # - pip install git+https://github.com/mobiusklein/glypy.git
  - git clone https://github.com/mobiusklein/glypy.git && cd glypy && python setup.py install && cd ..
  - git clone https://github.com/mobiusklein/glycopeptidepy.git && cd glycopeptidepy && python setup.py install && cd ..
  - pip install git+https://github.com/mobiusklein/ms_peak_picker.git
  - pip install psims
  - pip install git+https://github.com/mobiusklein/ms_deisotope.git
  - pip install git+https://github.com/mobiusklein/pysqlite.git
  - pip install PyInstaller
  - python setup.py install
script: make test build-pyinstaller