language: python
python:
  - "2.7"
cache: pip
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install Cython --install-option="--no-cython-compile"
  - pip install coverage pytest pytest-cov
  - pip install lxml pyteomics brain-isotopic-distribution
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -r external-requirements.txt
  - pip install git+https://github.com/mobiusklein/glypy.git
  - pip install git+https://github.com/mobiusklein/glycopeptidepygit
  - pip install git+https://github.com/mobiusklein/ms_peak_picker.git
  - pip install git+https://github.com/mobiusklein/ms_deisotope.git
script: make test